# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# CSTDM_processv2.py
# Created on: 2015-01-09 17:52:10.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
HwyNetwork_Loaded_PM_2010 = "HwyNetwork_Loaded_PM_2010"
HwyNetwork_Loaded_AM_2010 = "HwyNetwork_Loaded_AM_2010"
HwyNetwork_Loaded_MID_2010_shp = "H:\\Data_Received_from MPO\\CSTDM\\HwyNetwork_Loaded_MID_2010.shp"
HwyNetwork_Loaded_OFF_2010_shp = "H:\\Data_Received_from MPO\\CSTDM\\HwyNetwork_Loaded_OFF_2010.shp"
v2010 = "H:\\Data_Received_from MPO\\CSTDM\\2010"
HwyNetwork_Loaded_AM_2010_dbf = "H:\\Data_Received_from MPO\\CSTDM\\2010\\HwyNetwork_Loaded_AM_2010.dbf"
HwyNetwork_Loaded_MID_2010_dbf = "H:\\Data_Received_from MPO\\CSTDM\\2010\\HwyNetwork_Loaded_MID_2010.dbf"
HwyNetwork_Loaded_OFF_2010_dbf = "H:\\Data_Received_from MPO\\CSTDM\\2010\\HwyNetwork_Loaded_OFF_2010.dbf"
HwyNetwork_Loaded_PM_2010_dbf = "H:\\Data_Received_from MPO\\CSTDM\\2010\\HwyNetwork_Loaded_PM_2010.dbf"
Daily_2010_hdv = "Daily_2010_hdv"
HwyNetwork_Loaded_PM_2010__2_ = "HwyNetwork_Loaded_PM_2010"
HwyNetwork_Loaded_AM_2010__2_ = "HwyNetwork_Loaded_AM_2010"
HwyNetwork_Loaded_MID_2010_shp__2_ = "H:\\Data_Received_from MPO\\CSTDM\\HwyNetwork_Loaded_MID_2010.shp"
HwyNetwork_Loaded_OFF_2010_shp__2_ = "H:\\Data_Received_from MPO\\CSTDM\\HwyNetwork_Loaded_OFF_2010.shp"
HwyNetwork_Loaded_OFF_2010_shp__3_ = "H:\\Data_Received_from MPO\\CSTDM\\HwyNetwork_Loaded_OFF_2010.shp"
HwyNetwork_Loaded_OFF_2010_shp__4_ = "H:\\Data_Received_from MPO\\CSTDM\\HwyNetwork_Loaded_OFF_2010.shp"
HwyNetwork_Loaded_MID_2010_shp__3_ = "H:\\Data_Received_from MPO\\CSTDM\\HwyNetwork_Loaded_MID_2010.shp"
HwyNetwork_Loaded_AM_2010__3_ = "HwyNetwork_Loaded_AM_2010"
HwyNetwork_Loaded_PM_2010__3_ = "HwyNetwork_Loaded_PM_2010"
HwyNetwork_Loaded_MID_2010_shp__4_ = "H:\\Data_Received_from MPO\\CSTDM\\HwyNetwork_Loaded_MID_2010.shp"
HwyNetwork_Loaded_AM_2010__4_ = "HwyNetwork_Loaded_AM_2010"
HwyNetwork_Loaded_PM_2010__4_ = "HwyNetwork_Loaded_PM_2010"
HwyNetwork_Loaded_AM_2010_dbf__2_ = "H:\\Data_Received_from MPO\\CSTDM\\2010\\HwyNetwork_Loaded_AM_2010.dbf"
HwyNetwork_Loaded_MID_2010_dbf__2_ = "H:\\Data_Received_from MPO\\CSTDM\\2010\\HwyNetwork_Loaded_MID_2010.dbf"
HwyNetwork_Loaded_OFF_2010_dbf__2_ = "H:\\Data_Received_from MPO\\CSTDM\\2010\\HwyNetwork_Loaded_OFF_2010.dbf"
HwyNetwork_Loaded_PM_2010_dbf__2_ = "H:\\Data_Received_from MPO\\CSTDM\\2010\\HwyNetwork_Loaded_PM_2010.dbf"
HwyNetwork_Loaded_AM_2010_dbf__4_ = "H:\\Data_Received_from MPO\\CSTDM\\2010\\HwyNetwork_Loaded_AM_2010.dbf"
HwyNetwork_Loaded_MID_2010_dbf__3_ = "H:\\Data_Received_from MPO\\CSTDM\\2010\\HwyNetwork_Loaded_MID_2010.dbf"
HwyNetwork_Loaded_OFF_2010_dbf__4_ = "H:\\Data_Received_from MPO\\CSTDM\\2010\\HwyNetwork_Loaded_OFF_2010.dbf"
HwyNetwork_Loaded_PM_2010_dbf__3_ = "H:\\Data_Received_from MPO\\CSTDM\\2010\\HwyNetwork_Loaded_PM_2010.dbf"

# Process: Add Field
arcpy.AddField_management(HwyNetwork_Loaded_PM_2010, "PM", "DOUBLE", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field
arcpy.CalculateField_management(HwyNetwork_Loaded_PM_2010__2_, "PM", "[V4_2]+ [V5_2]+ [V6_2]+ [V10_2]+ [V14_2]+ [V15_2]", "VB", "")

# Process: Add Field (8)
arcpy.AddField_management(HwyNetwork_Loaded_PM_2010__3_, "PMSPD", "DOUBLE", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (8)
arcpy.CalculateField_management(HwyNetwork_Loaded_PM_2010__4_, "PMSPD", "[CSPD_2]", "VB", "")

# Process: Table to dBASE (multiple)
arcpy.TableToDBASE_conversion("HwyNetwork_Loaded_PM_2010", v2010)

# Process: Add Field (3)
arcpy.AddField_management(HwyNetwork_Loaded_MID_2010_shp, "MID", "DOUBLE", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (3)
arcpy.CalculateField_management(HwyNetwork_Loaded_MID_2010_shp__2_, "MID", "[V4_2]+ [V5_2]+ [V6_2]+ [V10_2]+ [V14_2]+ [V15_2]", "VB", "")

# Process: Add Field (6)
arcpy.AddField_management(HwyNetwork_Loaded_MID_2010_shp__3_, "MIDSPD", "DOUBLE", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (6)
arcpy.CalculateField_management(HwyNetwork_Loaded_MID_2010_shp__4_, "MIDSPD", "[CSPD_2]", "VB", "")

# Process: Table to dBASE (multiple) (2)
arcpy.TableToDBASE_conversion("'H:\\Data_Received_from MPO\\CSTDM\\HwyNetwork_Loaded_MID_2010.shp'", v2010)

# Process: Add Field (4)
arcpy.AddField_management(HwyNetwork_Loaded_OFF_2010_shp, "OFF", "DOUBLE", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (4)
arcpy.CalculateField_management(HwyNetwork_Loaded_OFF_2010_shp__2_, "OFF", "[V4_2]+ [V5_2]+ [V6_2]+ [V10_2]+ [V14_2]+ [V15_2]", "VB", "")

# Process: Add Field (5)
arcpy.AddField_management(HwyNetwork_Loaded_OFF_2010_shp__3_, "OFFSPD", "DOUBLE", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (5)
arcpy.CalculateField_management(HwyNetwork_Loaded_OFF_2010_shp__4_, "OFFSPD", "[CSPD_2]", "VB", "")

# Process: Table to dBASE (multiple) (3)
arcpy.TableToDBASE_conversion("'H:\\Data_Received_from MPO\\CSTDM\\HwyNetwork_Loaded_OFF_2010.shp'", v2010)

# Process: Add Field (2)
arcpy.AddField_management(HwyNetwork_Loaded_AM_2010, "AM", "DOUBLE", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (2)
arcpy.CalculateField_management(HwyNetwork_Loaded_AM_2010__2_, "AM", "[V4_2]+ [V5_2]+ [V6_2]+ [V10_2]+ [V14_2]+ [V15_2]", "VB", "")

# Process: Add Field (7)
arcpy.AddField_management(HwyNetwork_Loaded_AM_2010__3_, "AMSPD", "DOUBLE", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (7)
arcpy.CalculateField_management(HwyNetwork_Loaded_AM_2010__4_, "AMSPD", "[CSPD_2]", "VB", "")

# Process: Table to dBASE (multiple) (4)
arcpy.TableToDBASE_conversion("HwyNetwork_Loaded_AM_2010", v2010)

# Process: Add Field (9)
arcpy.AddField_management(HwyNetwork_Loaded_AM_2010_dbf, "Joinfld", "TEXT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (9)
arcpy.CalculateField_management(HwyNetwork_Loaded_AM_2010_dbf__2_, "Joinfld", "[A]&\"_\"& [B]", "VB", "")

# Process: Join Field
arcpy.JoinField_management(Daily_2010_hdv, "Join", HwyNetwork_Loaded_AM_2010_dbf__4_, "Joinfld", "AM;AMSPD")

# Process: Add Field (10)
arcpy.AddField_management(HwyNetwork_Loaded_MID_2010_dbf, "Joinfld", "TEXT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (10)
arcpy.CalculateField_management(HwyNetwork_Loaded_MID_2010_dbf__2_, "Joinfld", "[A]&\"_\"& [B]", "VB", "")

# Process: Join Field (2)
arcpy.JoinField_management(Daily_2010_hdv, "Join", HwyNetwork_Loaded_MID_2010_dbf__3_, "Joinfld", "MID;MIDSPD")

# Process: Add Field (11)
arcpy.AddField_management(HwyNetwork_Loaded_OFF_2010_dbf, "Joinfld", "TEXT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (11)
arcpy.CalculateField_management(HwyNetwork_Loaded_OFF_2010_dbf__2_, "Joinfld", "[A]&\"_\"&[B]", "VB", "")

# Process: Join Field (3)
arcpy.JoinField_management(Daily_2010_hdv, "Join", HwyNetwork_Loaded_OFF_2010_dbf__4_, "Joinfld", "OFF;OFFSPD;AM;AMSPD")

# Process: Add Field (12)
arcpy.AddField_management(HwyNetwork_Loaded_PM_2010_dbf, "Joinfld", "TEXT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (12)
arcpy.CalculateField_management(HwyNetwork_Loaded_PM_2010_dbf__2_, "Joinfld", "[A]&\"_\"& [B]", "VB", "")

# Process: Join Field (4)
arcpy.JoinField_management(Daily_2010_hdv, "Join", HwyNetwork_Loaded_PM_2010_dbf__3_, "Joinfld", "PM;PMSPD;AM;AMSPD")

